name: Runner test

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/runner-test.yml"

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "RK Logistics runner OK"
